name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y qemu-system gcc make && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
      
    - name: install i386
      run: sudo -s && wget https://raw.githubusercontent.com/lordmilko/i686-elf-tools/master/i686-elf-tools.sh &&chmod +x ./i686-elf-tools.sh &&./i686-elf-tools.sh

    - name: Run OS Script
      run: ./run_os.sh

    
